### PR TITLE
turn off bt for samsung by default. bump maps+gradle

### PR DESCRIPTION
**Pull request by bobzilladev**

### CODE REVIEW

**Comment by bobzilladev** [comment]
True, looks like almost all occurrences are samsung + motorola, guess they should be added too.

**Comment by bobzilladev** [comment]
Pushed change to add motorola.

**Comment by rksh** [comment]
**OS ver: 9,8.1:** 29% Galaxy Note9, 12.5% Nexus 6P, 12.5% Moto G5S Plus, 8.3% Moto G6 (others include Galaxy Tab A, S9+, J3, Nokia 6.1, Mi A1)
**OS ver: 8.0:** 16.7% HTC u11, 16.7% V30, 16.7% moto G6, 16.7% Galaxy J3, "" S7, 16.7% Moto Z 2 Play.
**OS ver: 7.0:** 33.3% Xperia Z5, 33.3% Galaxy Tab S2, 33.3% Qua Tab PX

**Comment by bobzilladev** [comment]
ark fixed this for real, closing.

**Pull request closed without merging**
