### PR TITLE
turn off notification sound

### PR DESCRIPTION
**Pull request by bobzilladev**

### CODE REVIEW

**Comment by bobzilladev** [comment]
Updated to just `channel.setSound(null,null)`

**Comment by bobzilladev** [comment]
Now checks for `samsung` to get HIGH

**Comment by bobzilladev** [comment]
now checks for `google` to _not_ get HIGH

**Comment by bobzilladev** [comment]
ok, now only does `setSound(null,null)`

**Review by rksh — APPROVED** [review]

**Pull request merged**
