### PR TITLE
FIX- handling two bug reports from email

### PR DESCRIPTION
**Pull request by rksh**
there are probably a lot more exceptions possible in the uploader case. :/

### CODE REVIEW

**Comment by bobzilladev** [comment]
This still looks like it is eating the error, since it's not assigned anywhere. How does this error get shown to the user?

**Comment by rksh** [comment]
Are you advocating for displaying the actual exception to the user? The null returns here both fail gracefully - showing unable-to-connect messages instead of dumping stack and crashing the app.

**Comment by bobzilladev** [comment]
This is better than crashing, but yes, i'd argue showing the error to the user. I'd like to make an activity where the user can see the last 20 lines of logging that i now keep around so they could at least investigate (or we could ask them to send it).

**Comment by bobzilladev** [comment]
Should we close this, since it sounds like these are already not app-crashing? The real fix is probably the flag saying whether this was an app-crashing stack?

**Pull request closed without merging**
