### PR TITLE
FIX - why not just prefer AES?

### PR DESCRIPTION
**Pull request by rksh**
I'm confused about how this worked at all.

### CODE REVIEW

**Comment by bobzilladev** [comment]
i think this is ok. all this code is thorny

**Comment by rksh** [comment]
this is our problem with LineageOS - we're seeing differing cipher compat in non-matching versions to the android mainline. getApiTokenVersion2 will never be called *unless* there's a keystore KEYSTORE_WIGLE_CREDS_KEY_V2 set - this isn't a proxy for an M check, but if it ...CREDS_KEY_V2 is set, then it was set in a version where we successfully generated a v2 keypair, which is a "good enough" test. same goes for KEYSTORE_WIGLE_CREDS_KEY_V1 and KEYSTORE_WIGLE_CREDS_KEY_V0 in order - if none are present, then we're safely in a plaintext situation. We never unset old aliases.

**Comment by bobzilladev** [comment]
Then even more-so it needs to be lined up, so either both places do the M check, or neither. With this PR only getApiTokenVersion2 is doing the M check, and if it fails it returns null, even if the key was actually set in the keystore.

**Comment by rksh** [comment]
Relaxed check to K - below that it will generate compiler warnings/errors (GCMParameterSpec not in < v19)

**Pull request merged**
